name: Cypress Tests

#Manually trigger a workflow
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
               
      - name: Gnerate HTML report
        run: npm run report:generate
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/work/Cypress/Cypress/TestReport.zip
          retention-days: 5
        
