name: Cypress Tests

#Manually trigger a workflow
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
               
       # Merge mochawesome report of each spec file and generate single html report        
      - name: Gnerate HTML reporte
        run: npm run report:generate
        
      - name: Tar files
        run: tar -cvf my_files.tar /home/runner/work/Cypress/Cypress/TestReport/
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my_files.tar
          retention-days: 15
      
     
