name: Cypress Tests

#Manually trigger a workflow
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
               
      - name: Gnerate HTML report
        run: npm run report:generate
      
      - name: Tar files
        run: tar -cvf my_files.tar /home/runner/work/Cypress/Cypress/TestReport/cypress-combined-report.html/to/https://github.com/Dehelpmate/Cypress

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my_files.tar
